image:
    name: 817396815769.dkr.ecr.eu-west-1.amazonaws.com/stefna/php:7.4-stable
    aws:
        access-key: $ECR_ACCESS_KEY
        secret-key: $ECR_SECRET_KEY


definitions:
    steps:
        -   step: &run-unit-test
                name: Unit tests
                caches:
                    - composer
                script:
                    - composer install -o
                    - vendor/bin/phpunit --log-junit ./test-reports/junit.xml

        -   step: &run-linter
                name: linter
                caches:
                    - composer
                script:
                    - composer install -o
                    - vendor/bin/phpcs -n --standard=vendor/stefna/codestyle/library.xml src/

        -   step: &run-phpstan
                name: phpstan
                caches:
                    - composer
                script:
                    - composer install -o
                    - vendor/bin/phpstan analyze --no-ansi --no-progress

pipelines:
    default:
        -   parallel:
                -   step: *run-linter
                -   step: *run-phpstan
